<a href="https://colab.research.google.com/github/ruthwick-2484/2024_stat_ml_assignment/blob/main/stml_project_2484.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv('/content/Maternal Health Risk Data Set.csv')
df

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]

In [ ]:
feature_col_names = ['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate']
predicted_class_names = ['RiskLevel']


X = df[feature_col_names].values
y = df[predicted_class_names].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# SVM

In [ ]:
from sklearn.svm import SVC
svm = SVC(kernel="rbf", C=2,random_state=0)
svm.fit(X_train, y_train.ravel())
y_pred = svm.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is: 0.6
              precision    recall  f1-score   support

   high risk       0.84      0.63      0.72        76
    low risk       0.52      0.95      0.67       117
    mid risk       0.69      0.21      0.33       112

    accuracy                           0.60       305
   macro avg       0.68      0.60      0.57       305
weighted avg       0.66      0.60      0.56       305

[[ 48  20   8]
 [  3 111   3]
 [  6  82  24]]


# KNN

In [ ]:
clf = KNeighborsClassifier()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is: 0.6098360655737705
              precision    recall  f1-score   support

   high risk       0.73      0.74      0.73        76
    low risk       0.57      0.74      0.64       117
    mid risk       0.57      0.39      0.47       112

    accuracy                           0.61       305
   macro avg       0.62      0.62      0.61       305
weighted avg       0.61      0.61      0.60       305

[[56  9 11]
 [ 9 86 22]
 [12 56 44]]


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


# Logistic Regression

In [ ]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is: 0.6327868852459017
              precision    recall  f1-score   support

   high risk       0.82      0.70      0.75        76
    low risk       0.56      0.91      0.69       117
    mid risk       0.67      0.30      0.42       112

    accuracy                           0.63       305
   macro avg       0.68      0.64      0.62       305
weighted avg       0.66      0.63      0.61       305

[[ 53  15   8]
 [  2 106   9]
 [ 10  68  34]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Perceptron Learning

In [ ]:
from sklearn.linear_model import Perceptron
pr = Perceptron()
pr.fit(X_train,y_train)
y_pred = pr.predict(X_test)
accu = accuracy_score(y_test,y_pred)
print("Accuracy is:", accu)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy is: 0.6032786885245902
              precision    recall  f1-score   support

   high risk       0.72      0.71      0.72        76
    low risk       0.60      0.56      0.58       117
    mid risk       0.54      0.58      0.56       112

    accuracy                           0.60       305
   macro avg       0.62      0.62      0.62       305
weighted avg       0.61      0.60      0.60       305

[[54 10 12]
 [ 8 65 44]
 [13 34 65]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
